config/routes.rb
Rails.application.routes.draw do
  root 'books#index'

  resources :books, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:create]
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
  validates :title,
    presence: true,
    uniqueness: { scope: :author }
  validates :author, presence: true
  validates :year, presence: true

  has_many :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
  validates :rating, presence: true, inclusion: { within: 1..5 }
  validates :body, presence: true
  validates :book, presence: true

  belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
    @review = Review.new
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      flash[:notice] = 'Success'
      redirect_to book_path(@book)
    else
      flash.now[:notice] = 'Error'
      render :new
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :author, :year, :description, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    @book = Book.find(params[:book_id])
    @review.book = @book

    if @review.save
      flash[:notice] = 'Success'
      redirect_to book_path(@book)
    else
      flash.now[:notice] = 'Error'
      render 'books/show'
    end
  end

  private
  def review_params
    params.require(:review).permit(:rating, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/index.html.erb
<h1>Current Book List</h1>

<table style="width:450px">
  <thead>
    <tr>
      <td>Title</td>
      <td>Author</td>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to book.title, book_path(book) %></td>
        <td><%= book.author %></td>
      </tr>
    <% end %>
  </tbody>
</table><br/>

app/views/books/new.html.erb
<h1>Add a Book </h1>

<%= simple_form_for @book do |f| %>
  <%= f.input :title %>
  <%= f.input :author %>
  <%= f.input :year %>
  <%= f.input :description %>
  <%= f.input :category %>
  <%= f.button :submit %>
<% end %>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>

<ul>
  <li>Author: <%= @book.author %></li>
  <li>Published: <%= @book.year %></li>
  <li>Description: <%= @book.description %></li>
  <li>Category: <%= @book.category %></li>
</ul>

<h2>Reviews</h2>
<div>
  <ul>
    <% @book.reviews.each do |review| %>
      <li>
        Rating: <%= review.rating %><br/>
        Body: <%= review.body %>
      </li>
    <% end %>
  </ul>
</div><br/>

<h2>Add a New Review</h2>
<div>
  <%= simple_form_for([@book, @review]) do |f| %>
    <%= f.input :rating, label: 'Rating (1-5)' %>
    <%= f.input :body %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bibiophile Book Club</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="nav-bar">
    <ul class="nav">
      <li id="title">Bibliophile Book Club</li>
      <div class="list">
        <li><%= link_to 'Add a New Book', new_book_path %></li>
        <li> | </li>
        <li><%= link_to 'Current Book List', books_path %></li>
      </div>
    </ul>
  </div>

<p><%= notice %></p>
<p><%= alert %></p>

<%= yield %>

</body>
</html>